name: "CI"

on: [push, pull_request]

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install Dependencies"
        run: "yarn install"
      - name: "Test"
        run: "yarn test"
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}