name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Test the contracts"
        run: "yarn run test"
